// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package example_mess is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	Boring
*/
package example_mess

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Boring struct {
	Cont             *string `protobuf:"bytes,1,req,name=cont" json:"cont,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Boring) Reset()         { *m = Boring{} }
func (m *Boring) String() string { return proto.CompactTextString(m) }
func (*Boring) ProtoMessage()    {}

func (m *Boring) GetCont() string {
	if m != nil && m.Cont != nil {
		return *m.Cont
	}
	return ""
}

func init() {
}
